### ISSUE TITLE
Splitter not compatible with Angular 19

### ISSUE THREAD

**Issue by RobertDr** [angular-split/angular-split#480]
The build of my app using angular-split fails with this error message:
./node_modules/angular-split/fesm2022/angular-split.mjs:1092:13-35 - Error: export 'ɵɵStandaloneFeature' (imported as 'i0') was not found in '@angular/core' (possible exports: ...

It seems, that the new Angular version does not export "ɵɵStandaloneFeature" any more.

**Comment by RobertDr** [comment]
Does anyone else have the same problem and possibly found a workaround?

**Comment by BrianMikinski** [comment]
This is holding me up as well. Would like to upgrade as soon as possible

**Comment by RobertDr** [comment]
There is already a pull request [Update19](https://github.com/angular-split/angular-split/pull/483) for a migration to Angular 19. Unfortunately this PR was declined due to failed tests.

**Comment by Jefiozie** [comment]
We are working on releasing it as soon as possible. The  PR is updated and we will try to do our best to release it soon.

**Comment by Jefiozie** [comment]
I've pushed out a beta release of 19: https://www.npmjs.com/package/angular-split/v/19.0.0-beta.0
Please let me know if this fixes  your issues.

**Comment by RobertDr** [comment]
My issues seems to be fixed with this beta release after some short tests. 
I will proceed with additional tests, when I'm back at work on January 2nd. 
But I don't expect additional problems, so I assume, this build may leave the beta state.
Thank you very much!

**Comment by Jefiozie** [comment]
@RobertDr thanks for providing me your feedback. I hope we can release it in the first weeks of January if nothing comes up in between or somebody reports a big bug

**Comment by RobertDr** [comment]
Just to confirm: after more tests, I still can't find a problem with my solution. I'm looking forward to the final release. 
Again: thank you very much!

**Comment by RobertDr** [comment]
Additional info: I get a deprecation warning in the browser console for each SplitComponent:

The 'allowSignalWrites' flag is deprecated and no longer impacts effect() (writes are always allowed)
SplitComponent | @ | angular-split.mjs:435
-- | SplitComponent_Factory | @ | angular-split.mjs:734

![image](https://github.com/user-attachments/assets/29b9f655-264e-4f4f-bb48-edd9ba834174)

**Comment by Harpush** [comment]
We should remove this flag in v19.
But anyway there is a draft PR that should discard the signal writing effect altogether: https://github.com/angular-split/angular-split/pull/455

**Comment by MaximeKoitsalu** [comment]
> Additional info: I get a deprecation warning in the browser console for each SplitComponent:
> 
> The 'allowSignalWrites' flag is deprecated and no longer impacts effect() (writes are always allowed) SplitComponent | @ | angular-split.mjs:435 -- | SplitComponent_Factory | @ | angular-split.mjs:734
> 
> ![image](https://github.com/user-attachments/assets/29b9f655-264e-4f4f-bb48-edd9ba834174)

Experiencing the same with `"angular-split": "^19.0.0-beta.2",`

**Comment by Jefiozie** [comment]
Hi @MaximeKoitsalu , just to confirm, you still see the warning in the latest beta release? The deprecation is correct there was q problem in our release cycle. We pushed a old version under a new tag.

**Comment by MaximeKoitsalu** [comment]
Hi @Jefiozie , my experience is that the split component still functions but I still see the warnings in my console. The stack trace points to:

`<as-split [direction]="node.direction" [id]="node.id" gutterSize="4" unit="percent">`

![Image](https://github.com/user-attachments/assets/6b535a23-2878-49da-b34e-a34519a2d5f1)

**Comment by RobertDr** [comment]
Yes, I still see this warning in the "19.0.0-beta.2" release.

It could be an important additional information, that these warnings are conly reported, when I'm running my development build using "ng serve", not when I'm running the production build using "ng build" (and hosted via IIS).

**Comment by Jefiozie** [comment]
I'm closing this issues as we just released a version 19. Feel free to reopen issues that are related to that version.
